In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("sales_data.csv")

In [5]:
df.head()

   order_id   product     category  sales  quantity region month
0       101  Keyboard  Electronics   1200         4  South   Jan
1       102     Mouse  Electronics    800         5  North   Jan
2       103     Chair    Furniture   4500         2   East   Feb
3       104      Desk    Furniture   7000         1   West   Feb
4       105   Monitor  Electronics  15000         3  South   Mar

In [6]:
df.shape

(8, 7)

<h5> Q1

In [7]:
# Select the rows where category is elctronics
df['category']== 'Electronics'                  # but dont want Boolean Table , we want all rows

0     True
1     True
2    False
3    False
4     True
5    False
6     True
7     True
Name: category, dtype: bool

In [8]:
df_elctronics = df[df['category']=='Electronics']

In [9]:
df_elctronics

   order_id   product     category  sales  quantity region month
0       101  Keyboard  Electronics   1200         4  South   Jan
1       102     Mouse  Electronics    800         5  North   Jan
4       105   Monitor  Electronics  15000         3  South   Mar
6       107     Mouse  Electronics    900         6   East   Apr
7       108  Keyboard  Electronics   1300         2   West   Apr

In [10]:
# .loc accesses direct columns name (label based)
df.loc[df['category']=='Electronics']

   order_id   product     category  sales  quantity region month
0       101  Keyboard  Electronics   1200         4  South   Jan
1       102     Mouse  Electronics    800         5  North   Jan
4       105   Monitor  Electronics  15000         3  South   Mar
6       107     Mouse  Electronics    900         6   East   Apr
7       108  Keyboard  Electronics   1300         2   West   Apr

<h5> Q2

In [11]:
# display row 2 to 5 and only column products and sales
df.iloc[2:6, [1,3]]                 # [rows, columns]

   product  sales
2    Chair   4500
3     Desk   7000
4  Monitor  15000
5     Lamp   1200

In [12]:
# Using .loc (label-based)
df.loc[2:5, ['product', 'sales']]

   product  sales
2    Chair   4500
3     Desk   7000
4  Monitor  15000
5     Lamp   1200

<h5> Q3

In [13]:
# retrieve the sales value of the row at index position 3
df.loc[3,'sales']               # scaler access

np.int64(7000)

In [14]:
df.loc[3]['sales']              # chained Indexing

np.int64(7000)

In [15]:
df.loc[3,['sales']]             # series access(returns pandas series)

sales    7000
Name: 3, dtype: object

<h5> Q4

In [16]:
# sort the dataframe by sales descending, but only first 3 rows
df.sort_values(by= 'sales',ascending=False).head(3)

   order_id  product     category  sales  quantity region month
4       105  Monitor  Electronics  15000         3  South   Mar
3       104     Desk    Furniture   7000         1   West   Feb
2       103    Chair    Furniture   4500         2   East   Feb

<h5> Q5

In [17]:
# compute total sales for each region
df.groupby('region')['sales'].sum()

region
East      5400
North     2000
South    16200
West      8300
Name: sales, dtype: int64

In [18]:
#also
df.groupby('region').agg({'sales':'sum'})

        sales
region
East     5400
North    2000
South   16200
West     8300

<h5> Q6

In [19]:
# compute the average qty sold for each category
df.groupby('category')['quantity'].mean()

category
Electronics    4.000000
Furniture      2.333333
Name: quantity, dtype: float64

<h5> Q7

In [20]:
# for each region , find highest sales value 
df.groupby('region')['sales'].max()

region
East      4500
North     1200
South    15000
West      7000
Name: sales, dtype: int64

In [21]:
# also, we can get index for max sales using idxmax
df.loc[df.groupby('region')['sales'].idxmax()]

   order_id  product     category  sales  quantity region month
2       103    Chair    Furniture   4500         2   East   Feb
5       106     Lamp    Furniture   1200         4  North   Mar
4       105  Monitor  Electronics  15000         3  South   Mar
3       104     Desk    Furniture   7000         1   West   Feb

<h5> Q8

In [22]:
# create a new summary dataframe with following metrics per region:
# total_sales
# avg_sales
# total_quantity

df.groupby('region').agg({'sales':['sum','mean'],'quantity':'sum'})

        sales         quantity
          sum    mean      sum
region
East     5400  2700.0        8
North    2000  1000.0        9
South   16200  8100.0        7
West     8300  4150.0        3

In [23]:
# Also
df.groupby('region').agg(total_sales= ('sales','sum'),
                         Avg_sales =('sales','mean'),
                         total_qty =('quantity','sum'))

        total_sales  Avg_sales  total_qty
region
East           5400     2700.0          8
North          2000     1000.0          9
South         16200     8100.0          7
West           8300     4150.0          3

<h5> Q9

In [24]:
# Melt the Dataframe
'''
id_vars : product, region, Month
value_vars : sales , quantity
result columns should be product ,region ,month ,metric, value
'''

'\nid_vars : product, region, Month\nvalue_vars : sales , quantity\nresult columns should be product ,region ,month ,metric, value\n'

In [25]:
df.melt(id_vars =['product', 'region','month'],
        value_vars =['sales','quantity'],           # turning from seperate column to rows
        var_name ='Metric',                         # new col name that will hold former column names(sales, quantity)
        value_name ='value')                        # new col name that will hold corresponding numeric values from sales and quantity
# converts wide format to long format

     product region month    Metric  value
0   Keyboard  South   Jan     sales   1200
1      Mouse  North   Jan     sales    800
2      Chair   East   Feb     sales   4500
3       Desk   West   Feb     sales   7000
4    Monitor  South   Mar     sales  15000
5       Lamp  North   Mar     sales   1200
6      Mouse   East   Apr     sales    900
7   Keyboard   West   Apr     sales   1300
8   Keyboard  South   Jan  quantity      4
9      Mouse  North   Jan  quantity      5
10     Chair   East   Feb  quantity      2
11      Desk   West   Feb  quantity      1
12   Monitor  South   Mar  quantity      3
13      Lamp  North   Mar  quantity      4
14     Mouse   East   Apr  quantity      6
15  Keyboard   West   Apr  quantity      2

----------------------------------------------------------------------------------
----------------------------------------------------------------------------------

In [26]:
df_region = pd.read_csv('region_target.csv')

In [27]:
df_region

  region  target_sales
0  North         50000
1  South         40000
2   East         45000
3   West         48000

<h5> Q1

In [29]:
# merge the two dataframes
df_merge = pd.merge(df, df_region, on='region', how ='left')
df_merge

   order_id   product     category  sales  quantity region month  target_sales
0       101  Keyboard  Electronics   1200         4  South   Jan         40000
1       102     Mouse  Electronics    800         5  North   Jan         50000
2       103     Chair    Furniture   4500         2   East   Feb         45000
3       104      Desk    Furniture   7000         1   West   Feb         48000
4       105   Monitor  Electronics  15000         3  South   Mar         40000
5       106      Lamp    Furniture   1200         4  North   Mar         50000
6       107     Mouse  Electronics    900         6   East   Apr         45000
7       108  Keyboard  Electronics   1300         2   West   Apr         48000

<h5> Q2

In [ ]:
# Add column as "Achievment_percentage" ( asssuming sale is price per item )
df_merge['Achievment_percent'] = ((df_merge['sales'] * df_merge['quantity'])/df_merge['target_sales']  )*100

In [35]:
df_merge

,order_id,product,category,sales,quantity,region,month,target_sales,Achievment_percent
0,101,Keyboard,Electronics,1200,4,South,Jan,40000,12.000000
1,102,Mouse,Electronics,800,5,North,Jan,50000,8.000000
2,103,Chair,Furniture,4500,2,East,Feb,45000,20.000000
3,104,Desk,Furniture,7000,1,West,Feb,48000,14.583333
4,105,Monitor,Electronics,15000,3,South,Mar,40000,112.500000
5,106,Lamp,Furniture,1200,4,North,Mar,50000,9.600000
6,107,Mouse,Electronics,900,6,East,Apr,45000,12.000000
7,108,Keyboard,Electronics,1300,2,West,Apr,48000,5.416667

In [36]:
# (assuming sales is total sales)

df_merge["Achievment_percent"] = df_merge['sales'] /df_merge['target_sales'] *100
df_merge

,order_id,product,category,sales,quantity,region,month,target_sales,Achievment_percent
0,101,Keyboard,Electronics,1200,4,South,Jan,40000,3.000000
1,102,Mouse,Electronics,800,5,North,Jan,50000,1.600000
2,103,Chair,Furniture,4500,2,East,Feb,45000,10.000000
3,104,Desk,Furniture,7000,1,West,Feb,48000,14.583333
4,105,Monitor,Electronics,15000,3,South,Mar,40000,37.500000
5,106,Lamp,Furniture,1200,4,North,Mar,50000,2.400000
6,107,Mouse,Electronics,900,6,East,Apr,45000,2.000000
7,108,Keyboard,Electronics,1300,2,West,Apr,48000,2.708333

In [39]:
# compute average achievment per region aand list the regions in descending order

df_achievement = df_merge.groupby('region')['Achievment_percent'].mean().sort_values(ascending=False)
df_achievement

region
South    20.250000
West      8.645833
East      6.000000
North     2.000000
Name: Achievment_percent, dtype: float64

<h5> Q3

In [44]:
# Identify which region is performing below 10% on average
df_below_10= df_achievement[df_achievement<10]
df_below_10

region
West     8.645833
East     6.000000
North    2.000000
Name: Achievment_percent, dtype: float64