In [1]:
import pandas as pd

df= pd.read_excel("customers.xlsx", sheet_name= 'customers')
df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

<h5><b><center> Attributes of DataFrame

In [2]:
df.index                    # Returns row labels of DF

RangeIndex(start=0, stop=1000, step=1)

In [3]:
df.shape                    # retruns dimensions of DF (rows, coulumns)

(1000, 11)

In [4]:
df.columns                  # returns index object of column labels

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'street_num',
       'street_name', 'street_suffix', 'city', 'state', 'postcode'],
      dtype='object')

In [5]:
df.dtypes                   # returns datatype of each column

id                 int64
first_name        object
last_name         object
email             object
gender            object
street_num       float64
street_name       object
street_suffix     object
city              object
state             object
postcode         float64
dtype: object

In [6]:
print(df['gender'].dtypes)                  # data type of individual columns

object

In [7]:
df.values                                   # return 2D numpy array of data

array([[1, 'Romain', 'Southcott', ..., 'San Diego', 'California',
        92127.0],
       [2, 'Cosimo', 'Molyneaux', ..., 'El Paso', 'Texas', nan],
       [3, 'Bambi', 'Westrip', ..., 'San Antonio', 'Texas', 78220.0],
       ...,
       [998, 'Tobit', 'Birt', ..., 'Waterbury', 'Connecticut', 6721.0],
       [999, 'Issiah', 'Standbrooke', ..., 'Savannah', 'Georgia',
        31405.0],
       [1000, 'Elmore', 'Malpas', ..., 'Atlanta', 'Georgia', 30386.0]],
      shape=(1000, 11), dtype=object)

In [8]:
df.size                                     # return number of elements

11000

In [9]:
df.empty                                    # True if DF is empty

False

In [10]:
df.ndim                                     # returns the number of dimensions

2

<h5><b><center> Methods of DataFrame

In [11]:
df.info()                                           # concise summary of DF

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   first_name     1000 non-null   object
 2   last_name      1000 non-null   object
 3   email          878 non-null    object
 4   gender         957 non-null    object
 5   street_num     738 non-null    float64
 6   street_name    963 non-null    object
 7   street_suffix  963 non-null    object
 8   city           921 non-null    object
 9   state          920 non-null    object
 10  postcode       843 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 86.1+ KB

In [12]:
df.head(3)                                  # returns the first n rows of DF

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0

In [13]:
df.tail(3)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [14]:
df.describe()                                   # returns descriptive stats of DF

                id    street_num      postcode
count  1000.000000    738.000000    843.000000
mean    500.500000  10536.439024  52669.548043
std     288.819436  23050.537603  28140.041026
min       1.000000      0.000000    214.000000
25%     250.750000     21.000000  29279.500000
50%     500.500000    445.500000  48232.000000
75%     750.250000   6918.500000  78337.500000
max    1000.000000  99918.000000  99812.000000

In [15]:
df.transpose()                              # swaps the rows and columns

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
id,1,2,3,4,5,6,7,8,9,10,...,991,992,993,994,995,996,997,998,999,1000
first_name,Romain,Cosimo,Bambi,Roarke,Mikaela,Magdalena,Marietta,Tine,Enrichetta,Sari,...,Susana,Silvie,Johnath,Binnie,Brana,Merrili,Winonah,Tobit,Issiah,Elmore
last_name,Southcott,Molyneaux,Westrip,Pankettman,Althorpe,Cullip,Heball,McSperrin,de Villier,Poulden,...,Pere,Silverlock,Clancy,Dearth,Dixon,Alman,Heckle,Birt,Standbrooke,Malpas
email,rsouthcott0@clickbank.net,cmolyneaux1@wiley.com,bwestrip2@symantec.com,rpankettman3@wiley.com,malthorpe4@51.la,mcullip5@tiny.cc,mheball6@blog.com,tmcsperrin7@statcounter.com,edevillier8@ox.ac.uk,spoulden9@xing.com,...,spereri@scribd.com,ssilverlockrj,jclancyrk@smugmug.com,bdearthrl@ed.gov,bdixonrm@myspace.com,malmanrn@cornell.edu,whecklero@fc2.com,NaN,istandbrookerq@yellowpages.com,NaN
gender,Male,Male,Female,Male,NaN,Female,Female,NaN,Female,Female,...,Female,Female,Female,NaN,Female,Female,Female,Male,Male,Male
street_num,1.0,NaN,4057.0,74.0,NaN,9190.0,12.0,530.0,745.0,2.0,...,5018.0,NaN,7.0,8993.0,97.0,0.0,701.0,2.0,NaN,205.0
street_name,Trailsway,NaN,Arkansas,Debs,2nd,Packers,Mallory,Erie,Annamark,Pond,...,Clemons,Elka,Washington,Elgar,Truax,Thompson,Rowland,Basil,Kenwood,Farwell
street_suffix,Road,NaN,Circle,Point,Drive,Drive,Center,Plaza,Street,Hill,...,Way,Avenue,Crossing,Trail,Avenue,Way,Hill,Road,Drive,Park
city,San Diego,El Paso,San Antonio,Memphis,NaN,Baltimore,Carol Stream,Kansas City,Fairbanks,New Orleans,...,Baton Rouge,Utica,Juneau,Minneapolis,Maple Plain,Reading,Indianapolis,Waterbury,Savannah,Atlanta
state,California,Texas,Texas,Tennessee,NaN,Maryland,Illinois,Missouri,Alaska,Louisiana,...,NaN,New York,Alaska,Minnesota,Minnesota,Pennsylvania,Indiana,Connecticut,Georgia,Georgia
postcode,92127.0,NaN,78220.0,38150.0,83732.0,21229.0,60351.0,64193.0,99709.0,NaN,...,70820.0,13505.0,99812.0,55441.0,55572.0,19610.0,46278.0,6721.0,31405.0,30386.0

<h5><b><center> Operations on rows and columns in DataFrames

In [16]:
                                        # Adding column to DF
df['Country']  ='USA'                   # adds new column name "Country" and assigns 'USA' value to all
df.head(3)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA

In [17]:
                                                # Adding column based on another column
df['full_name'] = df['first_name'] + ' ' + df['last_name']              # this adds column at the end
print('Customer Data with Full Name\n', df.head(3))

Customer Data with Full Name
    id first_name  last_name                      email  gender  street_num  \
0   1     Romain  Southcott  rsouthcott0@clickbank.net    Male         1.0
1   2     Cosimo  Molyneaux      cmolyneaux1@wiley.com    Male         NaN
2   3      Bambi    Westrip     bwestrip2@symantec.com  Female      4057.0

  street_name street_suffix         city       state  postcode Country  \
0   Trailsway          Road    San Diego  California   92127.0     USA
1         NaN           NaN      El Paso       Texas       NaN     USA
2    Arkansas        Circle  San Antonio       Texas   78220.0     USA

          full_name
0  Romain Southcott
1  Cosimo Molyneaux
2     Bambi Westrip

In [18]:
full_name = df['first_name'] + ' ' + df['last_name']
df.insert(3 ,'full_name2', full_name)                           # by this we can enter custom column at custom position

In [19]:
df.head(3)

,id,first_name,last_name,full_name2,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA,Cosimo Molyneaux
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA,Bambi Westrip

In [20]:
                                                    # Adding Row to DF
df.loc['1000'] = [1001,'sachin','khote','sachin khote','sachin@deloitte.com','Male',None, None, None,'California','California',92127.0,'USA','sachin khote']
df.tail(3)

C:\Users\sachi\AppData\Local\Temp\ipykernel_9920\1773679513.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df.loc['1000'] = [1001,'sachin','khote','sachin khote','sachin@deloitte.com','Male',None, None, None,'California','California',92127.0,'USA','sachin khote']

,id,first_name,last_name,full_name2,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA,Issiah Standbrooke
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA,Elmore Malpas
1000,1001,sachin,khote,sachin khote,sachin@deloitte.com,Male,NaN,None,None,California,California,92127.0,USA,sachin khote

In [21]:
                                                    # Deleting row or column
df.drop(index = '1000',inplace =True)               # removes last row 
df.tail(3)

,id,first_name,last_name,full_name2,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA,Tobit Birt
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA,Issiah Standbrooke
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA,Elmore Malpas

In [22]:
# deleting one or more columns

columns_to_drop = ['street_num', 'street_name','street_suffix']                 # removes three named columns
df.drop(columns = columns_to_drop , inplace=True)                               # inplace=True makes changes to original DF
df.head(3)

,id,first_name,last_name,full_name2,email,gender,city,state,postcode,Country,full_name
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,El Paso,Texas,NaN,USA,Cosimo Molyneaux
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,San Antonio,Texas,78220.0,USA,Bambi Westrip

In [23]:
# Renaming Row Labels

df.rename(index={0:"First"}).head(2)                # renames the first row lable to "First"

,id,first_name,last_name,full_name2,email,gender,city,state,postcode,Country,full_name
First,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,El Paso,Texas,NaN,USA,Cosimo Molyneaux

In [24]:
# making dictionary to mapp old index with new

rename_dict = {0:"first", 1:"second",2:'third',4:'fourth'}
df.rename(index = rename_dict).head()

,id,first_name,last_name,full_name2,email,gender,city,state,postcode,Country,full_name
first,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,San Diego,California,92127.0,USA,Romain Southcott
second,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,El Paso,Texas,NaN,USA,Cosimo Molyneaux
third,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,San Antonio,Texas,78220.0,USA,Bambi Westrip
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,Memphis,Tennessee,38150.0,USA,Roarke Pankettman
fourth,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,NaN,83732.0,USA,Mikaela Althorpe

In [25]:
# Renaming Column
df.rename(columns = {'first_name':'First Name', 'last_name':"Last Name"}).head(2)

,id,First Name,Last Name,full_name2,email,gender,city,state,postcode,Country,full_name
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,El Paso,Texas,NaN,USA,Cosimo Molyneaux

In [26]:
                                                    # Finding Unique Value along column(1 column)
unique = df['gender'].unique()
print("Unique genders are: ", unique)               # also there is no sense of finding it along rows, coz every next value will be different

Unique genders are:  ['Male' 'Female' nan]

In [27]:
# counting unique in gender
unique_count = df['gender'].nunique()
print("number of unique values in gender column:",unique_count)

number of unique values in gender column: 2

In [28]:
                                        # type Conversion
df_purchases = pd.read_excel('customers.xlsx',sheet_name='purchases')
df_purchases.dtypes             # just becasue paid column has $ in front of numbers, pandas is treating it as object

Unnamed: 0       int64
id               int64
purch_date      object
customer_num     int64
product_num      int64
amount           int64
paid            object
dtype: object

In [29]:
# converting the customer_num column to string coz we dont need any mathematical operation with that column
df_purchases['customer_num']= df_purchases['customer_num'].astype('str')
df_purchases.dtypes

Unnamed: 0       int64
id               int64
purch_date      object
customer_num    object
product_num      int64
amount           int64
paid            object
dtype: object

In [30]:
# converting the paid col to float type,by firstly removing $ by using replace function

df_purchases['paid'] = df_purchases['paid'].str.replace('$','').str.replace(',','').astype('float')

In [31]:
print(df_purchases.dtypes)                  # now the paid column is converted succesfully

Unnamed: 0        int64
id                int64
purch_date       object
customer_num     object
product_num       int64
amount            int64
paid            float64
dtype: object

In [32]:
# converting purch_date to date format
df_purchases.purch_date.head(2)                        # to check the date format of purch_datei.e., (yyyy-mm-dd hh:mm:ss)

0    2019-01-03 00:00:00
1    2019-01-03 00:00:00
Name: purch_date, dtype: object

In [33]:
pd.to_datetime(df_purchases['purch_date'])          # as we purch_date was already in standard format. therfore we didn't need to define format exclusively

0      2019-01-03
1      2019-01-03
2      2019-01-03
3      2019-01-03
4      2019-01-03
          ...
5995   2019-06-20
5996   2019-06-20
5997   2019-06-20
5998   2019-06-20
5999   2019-06-20
Name: purch_date, Length: 6000, dtype: datetime64[ns]

In [34]:
# but if we have any other date format other than standard one then we have to use format parameter
try:
    pd.to_datetime(df_purchases['purch_date'], format = '%Y-%M-%d %H:%m:%S')        # in format we pass the format of date time we already have in our column
except Exception as e:
    print("there is a date which is in 03/13/2019 this format\n",e)

there is a date which is in 03/13/2019 this format
 time data "03/13/2019" doesn't match format "%Y-%M-%d %H:%m:%S", at position 46. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

<h5><b><center> Join, Merge, Concat

In [35]:
# Concat
df_customers = pd.read_excel('customers.xlsx',sheet_name='customers')
df_purchases = pd.read_excel('customers.xlsx',sheet_name='purchases')
df_products = pd.read_excel('customers.xlsx',sheet_name ='products')

combined = pd.concat([df_customers, df_purchases, df_products],axis = 0)
combined

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Unnamed: 0,purch_date,customer_num,product_num,amount,paid,product,cost,company
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,Peach - Fresh,$20.53,Zazio
56,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,NaN,NaN,NaN,NaN,NaN,Muffin Hinge - 211n,$68.63,Fanoodle
57,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,NaN,NaN,NaN,NaN,NaN,Bar Bran Honey Nut,$73.05,Yakijo
58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN,"Nut - Almond, Blanched, Whole",$74.28,Eazzy
59,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,Table Cloth 90x90 Colour,$41.22,Quinu

In [36]:
combined_row_wise = pd.concat([df_customers, df_purchases, df_products],axis = 1)       # if DF have diff column names , pandas will create new column
combined_row_wise

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,...,purch_date,customer_num,product_num,amount,paid,Unnamed: 0,id,product,cost,company
0,1.0,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,...,2019-01-03 00:00:00,823,27,12,$568.92,0.0,1.0,Liners - Baking Cups,$6.36,Skipfire
1,2.0,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,...,2019-01-03 00:00:00,606,28,14,$395.36,1.0,2.0,Nori Sea Weed - Gold Label,$85.74,Dynazzy
2,3.0,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,...,2019-01-03 00:00:00,955,9,17,$510.17,2.0,3.0,Bar Bran Honey Nut,$65.40,Ntag
3,4.0,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,...,2019-01-03 00:00:00,577,19,3,$68.49,3.0,4.0,Soup - Campbells Beef Stew,$68.16,Photojam
4,5.0,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,...,2019-01-03 00:00:00,429,8,18,$759.42,4.0,5.0,Wine - Shiraz Wolf Blass Premium,$87.39,Eare
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,893,33,5,$411.10,NaN,NaN,NaN,NaN,NaN
5996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,566,23,11,$178.97,NaN,NaN,NaN,NaN,NaN
5997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,114,19,9,$205.47,NaN,NaN,NaN,NaN,NaN
5998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,404,11,20,$429.40,NaN,NaN,NaN,NaN,NaN
5999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,88,57,4,$274.52,NaN,NaN,NaN,NaN,NaN

In [37]:
# Merge (joins) - joins based on one or more keys.
merged_df = pd.merge(df_customers, df_purchases, on ='id', how ='inner')
merged_df.head(3)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Unnamed: 0,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,0,2019-01-03 00:00:00,823,27,12,$568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,1,2019-01-03 00:00:00,606,28,14,$395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,2,2019-01-03 00:00:00,955,9,17,$510.17

In [38]:
merged_right = pd.merge(df_customers ,df_purchases, on='id',how= 'right')
merged_right

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Unnamed: 0,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,0,2019-01-03 00:00:00,823,27,12,$568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,1,2019-01-03 00:00:00,606,28,14,$395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,2,2019-01-03 00:00:00,955,9,17,$510.17
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,3,2019-01-03 00:00:00,577,19,3,$68.49
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,4,2019-01-03 00:00:00,429,8,18,$759.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,5996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5995,06/20/2019,893,33,5,$411.10
5996,5997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5996,06/20/2019,566,23,11,$178.97
5997,5998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5997,06/20/2019,114,19,9,$205.47
5998,5999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5998,06/20/2019,404,11,20,$429.40
5999,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5999,06/20/2019,88,57,4,$274.52

In [39]:
pd.merge(df_purchases, df_customers,how ='left',left_on='customer_num',right_on='id')

,Unnamed: 0,id_x,purch_date,customer_num,product_num,amount,paid,id_y,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,0,1,2019-01-03 00:00:00,823,27,12,$568.92,823,Eldredge,Columbell,ecolumbellmu@squidoo.com,Male,NaN,Butterfield,Hill,Pompano Beach,Florida,33075.0
1,1,2,2019-01-03 00:00:00,606,28,14,$395.36,606,Beitris,Dulinty,bdulintygt@nasa.gov,Female,569.0,Dapin,Center,Oklahoma City,Oklahoma,73190.0
2,2,3,2019-01-03 00:00:00,955,9,17,$510.17,955,Belicia,Beddo,bbeddoqi@unblog.fr,Female,10.0,Mcguire,Hill,Dayton,Ohio,NaN
3,3,4,2019-01-03 00:00:00,577,19,3,$68.49,577,Ree,Chippendale,rchippendaleg0@bluehost.com,Female,4.0,NaN,NaN,Jefferson City,Missouri,65105.0
4,4,5,2019-01-03 00:00:00,429,8,18,$759.42,429,Denis,Perillo,dperillobw@odnoklassniki.ru,Male,83261.0,Melody,Point,Gary,Indiana,46406.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,5995,5996,06/20/2019,893,33,5,$411.10,893,Arman,Haste,ahasteos@constantcontact.com,Male,89637.0,NaN,NaN,Miami,NaN,33164.0
5996,5996,5997,06/20/2019,566,23,11,$178.97,566,Candida,Brazenor,cbrazenorfp@utexas.edu,Female,36652.0,Arapahoe,Terrace,Philadelphia,Pennsylvania,19109.0
5997,5997,5998,06/20/2019,114,19,9,$205.47,114,Carolus,Rosenshine,crosenshine35@booking.com,Male,89.0,Gulseth,Alley,Mansfield,Ohio,44905.0
5998,5998,5999,06/20/2019,404,11,20,$429.40,404,Cynthia,Habershaw,chabershawb7@live.com,Female,7122.0,Daystar,Plaza,Tallahassee,Florida,32399.0
5999,5999,6000,06/20/2019,88,57,4,$274.52,88,Baxie,Bridger,bbridger2f@1und1.de,NaN,79016.0,Havey,Circle,Cincinnati,Ohio,45208.0

In [40]:
# OverLapping Column names

customers = pd.DataFrame({'id':[1,2,3],
                          'first_name':['sachin','dada','baba'], 
                          'product':['Book','pen','notebook']})
purchase = pd.DataFrame({'id':[2,3,4],
                         'product':['pen','notebook','pencil'],
                         'amount':[5,10,15]})
merged_df = pd.merge(customers , purchase , on='id', how='inner',suffixes =('_cust','_pur'))

print("Merged Dataset with Suffixes:\n",merged_df)

Merged Dataset with Suffixes:
    id first_name product_cust product_pur  amount
0   2       dada          pen         pen       5
1   3       baba     notebook    notebook      10

In [41]:
# Joining

joined_df = df_customers.set_index('id').join(df_purchases)
print("Joined DataFrame\n",joined_df)

Joined DataFrame
      first_name    last_name                           email  gender  \
id
1        Romain    Southcott       rsouthcott0@clickbank.net    Male
2        Cosimo    Molyneaux           cmolyneaux1@wiley.com    Male
3         Bambi      Westrip          bwestrip2@symantec.com  Female
4        Roarke   Pankettman          rpankettman3@wiley.com    Male
5       Mikaela     Althorpe                malthorpe4@51.la     NaN
...         ...          ...                             ...     ...
996     Merrili        Alman            malmanrn@cornell.edu  Female
997     Winonah       Heckle               whecklero@fc2.com  Female
998       Tobit         Birt                             NaN    Male
999      Issiah  Standbrooke  istandbrookerq@yellowpages.com    Male
1000     Elmore       Malpas                             NaN    Male

      street_num street_name street_suffix          city         state  \
id
1            1.0   Trailsway          Road     San Diego    California
2            NaN         NaN           NaN       El Paso         Texas
3         4057.0    Arkansas        Circle   San Antonio         Texas
4           74.0        Debs         Point       Memphis     Tennessee
5            NaN         2nd         Drive           NaN           NaN
...          ...         ...           ...           ...           ...
996          0.0    Thompson           Way       Reading  Pennsylvania
997        701.0     Rowland          Hill  Indianapolis       Indiana
998          2.0       Basil          Road     Waterbury   Connecticut
999          NaN     Kenwood         Drive      Savannah       Georgia
1000       205.0     Farwell          Park       Atlanta       Georgia

      postcode  Unnamed: 0    id           purch_date  customer_num  \
id
1      92127.0           1     2  2019-01-03 00:00:00           606
2          NaN           2     3  2019-01-03 00:00:00           955
3      78220.0           3     4  2019-01-03 00:00:00           577
4      38150.0           4     5  2019-01-03 00:00:00           429
5      83732.0           5     6  2019-01-03 00:00:00           275
...        ...         ...   ...                  ...           ...
996    19610.0         996   997  2019-06-04 00:00:00            96
997    46278.0         997   998  2019-06-04 00:00:00           181
998     6721.0         998   999  2019-06-04 00:00:00           951
999    31405.0         999  1000  2019-06-04 00:00:00           435
1000   30386.0        1000  1001  2019-06-04 00:00:00           702

      product_num  amount       paid
id
1              28      14    $395.36
2               9      17    $510.17
3              19       3     $68.49
4               8      18    $759.42
5              36      18    $176.76
...           ...     ...        ...
996            27      14    $663.74
997             7       2     $27.66
998            54       4     $87.68
999            20      18  $1,143.90
1000           49      19    $677.92

[1000 rows x 17 columns]

<h5><b><center> Missing Values

In [42]:
null_values = df_customers.isnull()
print("using isnull():\n",null_values)

using isnull():
         id  first_name  last_name  email  gender  street_num  street_name  \
0    False       False      False  False   False       False        False
1    False       False      False  False   False        True         True
2    False       False      False  False   False       False        False
3    False       False      False  False   False       False        False
4    False       False      False  False    True        True        False
..     ...         ...        ...    ...     ...         ...          ...
995  False       False      False  False   False       False        False
996  False       False      False  False   False       False        False
997  False       False      False   True   False       False        False
998  False       False      False  False   False        True        False
999  False       False      False   True   False       False        False

     street_suffix   city  state  postcode
0            False  False  False     False
1             True  False  False      True
2            False  False  False     False
3            False  False  False     False
4            False   True   True     False
..             ...    ...    ...       ...
995          False  False  False     False
996          False  False  False     False
997          False  False  False     False
998          False  False  False     False
999          False  False  False     False

[1000 rows x 11 columns]

In [43]:
na_value =df_customers.isna()
print("using isna():\n",na_value)

using isna():
         id  first_name  last_name  email  gender  street_num  street_name  \
0    False       False      False  False   False       False        False
1    False       False      False  False   False        True         True
2    False       False      False  False   False       False        False
3    False       False      False  False   False       False        False
4    False       False      False  False    True        True        False
..     ...         ...        ...    ...     ...         ...          ...
995  False       False      False  False   False       False        False
996  False       False      False  False   False       False        False
997  False       False      False   True   False       False        False
998  False       False      False  False   False        True        False
999  False       False      False   True   False       False        False

     street_suffix   city  state  postcode
0            False  False  False     False
1             True  False  False      True
2            False  False  False     False
3            False  False  False     False
4            False   True   True     False
..             ...    ...    ...       ...
995          False  False  False     False
996          False  False  False     False
997          False  False  False     False
998          False  False  False     False
999          False  False  False     False

[1000 rows x 11 columns]

In [44]:
# check missing value for partucular column
is_null = df_customers['email'].isnull()
print(is_null[is_null])                             # returns all True

24     True
30     True
38     True
48     True
49     True
       ...
973    True
976    True
981    True
997    True
999    True
Name: email, Length: 122, dtype: bool

In [45]:
df_customers[~is_null]                          # Use ~ to invert the mask and get rows where isnull was False

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
993,994,Binnie,Dearth,bdearthrl@ed.gov,NaN,8993.0,Elgar,Trail,Minneapolis,Minnesota,55441.0
994,995,Brana,Dixon,bdixonrm@myspace.com,Female,97.0,Truax,Avenue,Maple Plain,Minnesota,55572.0
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0

In [46]:
not_null = df_customers['email'].notnull()
print(df_customers[not_null])                       # returns all non-null values columns

      id first_name    last_name                           email  gender  \
0      1     Romain    Southcott       rsouthcott0@clickbank.net    Male
1      2     Cosimo    Molyneaux           cmolyneaux1@wiley.com    Male
2      3      Bambi      Westrip          bwestrip2@symantec.com  Female
3      4     Roarke   Pankettman          rpankettman3@wiley.com    Male
4      5    Mikaela     Althorpe                malthorpe4@51.la     NaN
..   ...        ...          ...                             ...     ...
993  994     Binnie       Dearth                bdearthrl@ed.gov     NaN
994  995      Brana        Dixon            bdixonrm@myspace.com  Female
995  996    Merrili        Alman            malmanrn@cornell.edu  Female
996  997    Winonah       Heckle               whecklero@fc2.com  Female
998  999     Issiah  Standbrooke  istandbrookerq@yellowpages.com    Male

     street_num street_name street_suffix          city         state  \
0           1.0   Trailsway          Road     San Diego    California
1           NaN         NaN           NaN       El Paso         Texas
2        4057.0    Arkansas        Circle   San Antonio         Texas
3          74.0        Debs         Point       Memphis     Tennessee
4           NaN         2nd         Drive           NaN           NaN
..          ...         ...           ...           ...           ...
993      8993.0       Elgar         Trail   Minneapolis     Minnesota
994        97.0       Truax        Avenue   Maple Plain     Minnesota
995         0.0    Thompson           Way       Reading  Pennsylvania
996       701.0     Rowland          Hill  Indianapolis       Indiana
998         NaN     Kenwood         Drive      Savannah       Georgia

     postcode
0     92127.0
1         NaN
2     78220.0
3     38150.0
4     83732.0
..        ...
993   55441.0
994   55572.0
995   19610.0
996   46278.0
998   31405.0

[878 rows x 11 columns]

In [47]:
# check for missing values in each column:

missing_in_col =df_customers.isnull().any()
print("missing values in each column:\n",missing_in_col)

missing values in each column:
 id               False
first_name       False
last_name        False
email             True
gender            True
street_num        True
street_name       True
street_suffix     True
city              True
state             True
postcode          True
dtype: bool

In [48]:
# to find number of NaN/ missing values in column,then we use sum() along with isnull()

nan_counts = df_customers.isnull().sum()
print("number of NaN values per attribute:",nan_counts)

number of NaN values per attribute: id                 0
first_name         0
last_name          0
email            122
gender            43
street_num       262
street_name       37
street_suffix     37
city              79
state             80
postcode         157
dtype: int64

In [49]:
print(df_customers['email'].isnull().sum())             # for any particular column

122

In [50]:
# to find NaN count for each row

nan_rowise = df_customers.isnull().sum(axis=1)          # axis 1 for horizontal and 1 for vertical
print(nan_rowise)

0      0
1      4
2      0
3      0
4      4
      ..
995    0
996    0
997    1
998    1
999    1
Length: 1000, dtype: int64

In [51]:
# to find NaN values in whole dataset
nan_whole = df_customers.isnull().sum().sum()
print("NaN values across whole document are:",nan_whole)

NaN values across whole document are: 817

In [52]:
# Replacing Non-convertible values with pd.NA 
df_purchases['paid'].replace('unknown',pd.NA)

0       $568.92
1       $395.36
2       $510.17
3        $68.49
4       $759.42
         ...
5995    $411.10
5996    $178.97
5997    $205.47
5998    $429.40
5999    $274.52
Name: paid, Length: 6000, dtype: object

In [55]:
# or 
df_purchase_copy = df_purchases.copy()
df_purchase_copy['paid']=pd.to_numeric(df_purchase_copy['paid'],errors ='coerce')

In [56]:
df_purchase_copy.head(3)       # all converted to NaN coz all values had $ infront of it (so those values cannot be converted to numeric)

,Unnamed: 0,id,purch_date,customer_num,product_num,amount,paid
0,0,1,2019-01-03 00:00:00,823,27,12,NaN
1,1,2,2019-01-03 00:00:00,606,28,14,NaN
2,2,3,2019-01-03 00:00:00,955,9,17,NaN

In [57]:
# 'mixed' tells Pandas to handle both 2025/09/23 and 2024-05-13 formats
# 'coerce' turns 'unknown' into NaT automatically

df_purchase_copy['purch_date'] = pd.to_datetime(df_purchase_copy['purch_date'], format='mixed', errors='coerce')
df_purchase_copy

      Unnamed: 0    id purch_date  customer_num  product_num  amount  paid
0              0     1 2019-01-03           823           27      12   NaN
1              1     2 2019-01-03           606           28      14   NaN
2              2     3 2019-01-03           955            9      17   NaN
3              3     4 2019-01-03           577           19       3   NaN
4              4     5 2019-01-03           429            8      18   NaN
...          ...   ...        ...           ...          ...     ...   ...
5995        5995  5996 2019-06-20           893           33       5   NaN
5996        5996  5997 2019-06-20           566           23      11   NaN
5997        5997  5998 2019-06-20           114           19       9   NaN
5998        5998  5999 2019-06-20           404           11      20   NaN
5999        5999  6000 2019-06-20            88           57       4   NaN

[6000 rows x 7 columns]

In [59]:
                                                # Dropping Missing Values
# dropping rows with missing values
customers_copy = df_customers.copy()

customers_dropped_row = customers_copy.dropna()     # by default it drops rows , if we want to drop any missing value colm we have to change axis 
customers_dropped_row                               # returns only 418 rows , which means there are lot of rows which are dropped

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0
...,...,...,...,...,...,...,...,...,...,...,...
988,989,Vivianne,Abbyss,vabbyssrg@squarespace.com,Female,53592.0,Larry,Road,Santa Cruz,California,95064.0
992,993,Johnath,Clancy,jclancyrk@smugmug.com,Female,7.0,Washington,Crossing,Juneau,Alaska,99812.0
994,995,Brana,Dixon,bdixonrm@myspace.com,Female,97.0,Truax,Avenue,Maple Plain,Minnesota,55572.0
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0

In [61]:
customers_dropped_colm = customers_copy.dropna(axis =1)
customers_dropped_colm.head(3)

   id first_name  last_name
0   1     Romain  Southcott
1   2     Cosimo  Molyneaux
2   3      Bambi    Westrip

In [66]:
                                                # Imputing Missing Values
df_customers['email'].fillna('Unknown',inplace =True)
df_customers.tail(3)                            # we can clearly see the Unknown is placed at missing values place

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
997,998,Tobit,Birt,Unknown,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,Unknown,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [72]:
# filling missing values in gender column with mode(most frequent value)

gender_mode = df_customers['gender'].mode()[0]          
#mode(), returns series as 'Male' for which to acces its element we used [0] ,
# [0] to extract mode value from pandas series
df_customers['gender'].fillna(gender_mode , inplace =True)
df_customers

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,Unknown,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,Unknown,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [77]:
missing_street = df_customers[df_customers['street_num'].isna()]
missing_street.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,NaN,2nd,Drive,NaN,NaN,83732.0
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,NaN,Claremont,Place,Los Angeles,California,90005.0
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,NaN,Northwestern,Way,Amarillo,Texas,79118.0
20,21,Karim,Woosnam,kwoosnamk@ifeng.com,Male,NaN,Grayhawk,Place,Houston,Texas,NaN

In [80]:
df_customers['street_num'].fillna(method='ffill',inplace=True)
df_customers.head()                         # see id row 2 and 5 values in street_num got filled with previous values

C:\Users\sachi\AppData\Local\Temp\ipykernel_9920\1438360423.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_customers['street_num'].fillna(method='ffill',inplace=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_9920\1438360423.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_customers['street_num'].fillna(method='ffill',inplace=True)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,NaN,NaN,83732.0

In [82]:
df_customers['street_name'].fillna(method='bfill',inplace=True)
df_customers.head()                                     # see street_name of id row 2 got filled with its next value which is "Arkansas"

C:\Users\sachi\AppData\Local\Temp\ipykernel_9920\928498772.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_customers['street_name'].fillna(method='bfill',inplace=True)
C:\Users\sachi\AppData\Local\Temp\ipykernel_9920\928498772.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_customers['street_name'].fillna(method='bfill',inplace=True)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,Arkansas,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,NaN,NaN,83732.0

In [85]:
                    # also we can write it as 
df_customers['street_suffix'] = df_customers['street_suffix'].ffill()
df_customers.head()                                     # see this way also works the same and wont raise warning aswell.

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,Arkansas,Road,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,NaN,NaN,83732.0

In [87]:
# similarly we will fill all the remaining missign values by checking them first
df_customers.isna().sum()

id                 0
first_name         0
last_name          0
email              0
gender             0
street_num         0
street_name        0
street_suffix      0
city              79
state             80
postcode         157
dtype: int64

In [88]:
df_customers['city'] = df_customers['city'].bfill()
df_customers['state']= df_customers['state'].bfill()
df_customers['postcode'] = df_customers['postcode'].bfill()

df_customers.isna().sum()               # all 0 , good to go

id               0
first_name       0
last_name        0
email            0
gender           0
street_num       0
street_name      0
street_suffix    0
city             0
state            0
postcode         0
dtype: int64

In [89]:
                                                # dropping Duplicates
customer_unique = df_customers.drop_duplicates(subset = 'first_name')  # removes duplicates based on 'first_name' 
customer_unique                                     # data dropped down to 932 rows from 1000

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,Arkansas,Road,El Paso,Texas,78220.0
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,Baltimore,Maryland,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
994,995,Brana,Dixon,bdixonrm@myspace.com,Female,97.0,Truax,Avenue,Maple Plain,Minnesota,55572.0
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,Unknown,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
999,1000,Elmore,Malpas,Unknown,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

<h5><b><center> Aggregation

In [ ]:
df_purchase_copy.aggregate('max')                       # but for this all columns needs to have values which can be aggregated otherwise will raise error

Unnamed: 0                     5999
id                             6000
purch_date      2019-12-06 00:00:00
customer_num                   1000
product_num                      60
amount                           20
paid                            NaN
dtype: object

In [ ]:
df_purchases.select_dtypes(include ='number').aggregate('max')      

# This automatically grabs all 'int' and 'float' columns 
# and ignores strings/categorical columns.

Unnamed: 0      5999
id              6000
customer_num    1000
product_num       60
amount            20
dtype: int64

In [100]:
df_products['cost'].aggregate(['max','min'])            # selects particular column only

max    $99.54
min    $13.83
Name: cost, dtype: object

In [ ]:
# group by 

aggre_purchase = df_purchase_copy.groupby('purch_date').agg({'amount':'sum','paid':'sum'})
print(aggre_purchase)                                               # this groupes by the amount and paid column on the basis of dates

            amount  paid
purch_date
2019-01-03     480   0.0
2019-01-04     872   0.0
2019-01-05     715   0.0
2019-01-06     576   0.0
2019-02-03     568   0.0
...            ...   ...
2019-11-06     475   0.0
2019-12-03     524   0.0
2019-12-04     647   0.0
2019-12-05     380   0.0
2019-12-06     481   0.0

[108 rows x 2 columns]