In [3]:
import pandas as pd

df= pd.read_excel("customers.xlsx", sheet_name= 'customers')
df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

<h5><b><center> Attributes of DataFrame

In [4]:
df.index                    # Returns row labels of DF

RangeIndex(start=0, stop=1000, step=1)

In [5]:
df.shape                    # retruns dimensions of DF (rows, coulumns)

(1000, 11)

In [6]:
df.columns                  # returns index object of column labels

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'street_num',
       'street_name', 'street_suffix', 'city', 'state', 'postcode'],
      dtype='object')

In [7]:
df.dtypes                   # returns datatype of each column

id                 int64
first_name        object
last_name         object
email             object
gender            object
street_num       float64
street_name       object
street_suffix     object
city              object
state             object
postcode         float64
dtype: object

In [8]:
print(df['gender'].dtypes)                  # data type of individual columns

object

In [9]:
df.values                                   # return 2D numpy array of data

array([[1, 'Romain', 'Southcott', ..., 'San Diego', 'California',
        92127.0],
       [2, 'Cosimo', 'Molyneaux', ..., 'El Paso', 'Texas', nan],
       [3, 'Bambi', 'Westrip', ..., 'San Antonio', 'Texas', 78220.0],
       ...,
       [998, 'Tobit', 'Birt', ..., 'Waterbury', 'Connecticut', 6721.0],
       [999, 'Issiah', 'Standbrooke', ..., 'Savannah', 'Georgia',
        31405.0],
       [1000, 'Elmore', 'Malpas', ..., 'Atlanta', 'Georgia', 30386.0]],
      shape=(1000, 11), dtype=object)

In [10]:
df.size                                     # return number of elements

11000

In [11]:
df.empty                                    # True if DF is empty

False

In [12]:
df.ndim                                     # returns the number of dimensions

2

<h5><b><center> Methods of DataFrame

In [13]:
df.info()                                           # concise summary of DF

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   first_name     1000 non-null   object
 2   last_name      1000 non-null   object
 3   email          878 non-null    object
 4   gender         957 non-null    object
 5   street_num     738 non-null    float64
 6   street_name    963 non-null    object
 7   street_suffix  963 non-null    object
 8   city           921 non-null    object
 9   state          920 non-null    object
 10  postcode       843 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 86.1+ KB

In [14]:
df.head(3)                                  # returns the first n rows of DF

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0

In [15]:
df.tail(3)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [16]:
df.describe()                                   # returns descriptive stats of DF

                id    street_num      postcode
count  1000.000000    738.000000    843.000000
mean    500.500000  10536.439024  52669.548043
std     288.819436  23050.537603  28140.041026
min       1.000000      0.000000    214.000000
25%     250.750000     21.000000  29279.500000
50%     500.500000    445.500000  48232.000000
75%     750.250000   6918.500000  78337.500000
max    1000.000000  99918.000000  99812.000000

In [17]:
df.transpose()                              # swaps the rows and columns

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
id,1,2,3,4,5,6,7,8,9,10,...,991,992,993,994,995,996,997,998,999,1000
first_name,Romain,Cosimo,Bambi,Roarke,Mikaela,Magdalena,Marietta,Tine,Enrichetta,Sari,...,Susana,Silvie,Johnath,Binnie,Brana,Merrili,Winonah,Tobit,Issiah,Elmore
last_name,Southcott,Molyneaux,Westrip,Pankettman,Althorpe,Cullip,Heball,McSperrin,de Villier,Poulden,...,Pere,Silverlock,Clancy,Dearth,Dixon,Alman,Heckle,Birt,Standbrooke,Malpas
email,rsouthcott0@clickbank.net,cmolyneaux1@wiley.com,bwestrip2@symantec.com,rpankettman3@wiley.com,malthorpe4@51.la,mcullip5@tiny.cc,mheball6@blog.com,tmcsperrin7@statcounter.com,edevillier8@ox.ac.uk,spoulden9@xing.com,...,spereri@scribd.com,ssilverlockrj,jclancyrk@smugmug.com,bdearthrl@ed.gov,bdixonrm@myspace.com,malmanrn@cornell.edu,whecklero@fc2.com,NaN,istandbrookerq@yellowpages.com,NaN
gender,Male,Male,Female,Male,NaN,Female,Female,NaN,Female,Female,...,Female,Female,Female,NaN,Female,Female,Female,Male,Male,Male
street_num,1.0,NaN,4057.0,74.0,NaN,9190.0,12.0,530.0,745.0,2.0,...,5018.0,NaN,7.0,8993.0,97.0,0.0,701.0,2.0,NaN,205.0
street_name,Trailsway,NaN,Arkansas,Debs,2nd,Packers,Mallory,Erie,Annamark,Pond,...,Clemons,Elka,Washington,Elgar,Truax,Thompson,Rowland,Basil,Kenwood,Farwell
street_suffix,Road,NaN,Circle,Point,Drive,Drive,Center,Plaza,Street,Hill,...,Way,Avenue,Crossing,Trail,Avenue,Way,Hill,Road,Drive,Park
city,San Diego,El Paso,San Antonio,Memphis,NaN,Baltimore,Carol Stream,Kansas City,Fairbanks,New Orleans,...,Baton Rouge,Utica,Juneau,Minneapolis,Maple Plain,Reading,Indianapolis,Waterbury,Savannah,Atlanta
state,California,Texas,Texas,Tennessee,NaN,Maryland,Illinois,Missouri,Alaska,Louisiana,...,NaN,New York,Alaska,Minnesota,Minnesota,Pennsylvania,Indiana,Connecticut,Georgia,Georgia
postcode,92127.0,NaN,78220.0,38150.0,83732.0,21229.0,60351.0,64193.0,99709.0,NaN,...,70820.0,13505.0,99812.0,55441.0,55572.0,19610.0,46278.0,6721.0,31405.0,30386.0

<h5><b><center> Operations on rows and columns in DataFrames

In [18]:
                                        # Adding column to DF
df['Country']  ='USA'                   # adds new column name "Country" and assigns 'USA' value to all
df.head(3)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA

In [19]:
                                                # Adding column based on another column
df['full_name'] = df['first_name'] + ' ' + df['last_name']              # this adds column at the end
print('Customer Data with Full Name\n', df.head(3))

Customer Data with Full Name
    id first_name  last_name                      email  gender  street_num  \
0   1     Romain  Southcott  rsouthcott0@clickbank.net    Male         1.0
1   2     Cosimo  Molyneaux      cmolyneaux1@wiley.com    Male         NaN
2   3      Bambi    Westrip     bwestrip2@symantec.com  Female      4057.0

  street_name street_suffix         city       state  postcode Country  \
0   Trailsway          Road    San Diego  California   92127.0     USA
1         NaN           NaN      El Paso       Texas       NaN     USA
2    Arkansas        Circle  San Antonio       Texas   78220.0     USA

          full_name
0  Romain Southcott
1  Cosimo Molyneaux
2     Bambi Westrip

In [20]:
full_name = df['first_name'] + ' ' + df['last_name']
df.insert(3 ,'full_name2', full_name)                           # by this we can enter custom column at custom position

In [21]:
df.head(3)

,id,first_name,last_name,full_name2,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,USA,Cosimo Molyneaux
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,USA,Bambi Westrip

In [22]:
                                                    # Adding Row to DF
df.loc['1000'] = [1001,'sachin','khote','sachin khote','sachin@deloitte.com','Male',None, None, None,'California','California',92127.0,'USA','sachin khote']
df.tail(3)

C:\Users\sachi\AppData\Local\Temp\ipykernel_10092\1773679513.py:2: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df.loc['1000'] = [1001,'sachin','khote','sachin khote','sachin@deloitte.com','Male',None, None, None,'California','California',92127.0,'USA','sachin khote']

,id,first_name,last_name,full_name2,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA,Issiah Standbrooke
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA,Elmore Malpas
1000,1001,sachin,khote,sachin khote,sachin@deloitte.com,Male,NaN,None,None,California,California,92127.0,USA,sachin khote

In [23]:
                                                    # Deleting row or column
df.drop(index = '1000',inplace =True)               # removes last row 
df.tail(3)

,id,first_name,last_name,full_name2,email,gender,street_num,street_name,street_suffix,city,state,postcode,Country,full_name
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,USA,Tobit Birt
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,USA,Issiah Standbrooke
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,USA,Elmore Malpas

In [24]:
# deleting one or more columns

columns_to_drop = ['street_num', 'street_name','street_suffix']                 # removes three named columns
df.drop(columns = columns_to_drop , inplace=True)                               # inplace=True makes changes to original DF
df.head(3)

,id,first_name,last_name,full_name2,email,gender,city,state,postcode,Country,full_name
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,El Paso,Texas,NaN,USA,Cosimo Molyneaux
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,San Antonio,Texas,78220.0,USA,Bambi Westrip

In [25]:
# Renaming Row Labels

df.rename(index={0:"First"}).head(2)                # renames the first row lable to "First"

,id,first_name,last_name,full_name2,email,gender,city,state,postcode,Country,full_name
First,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,El Paso,Texas,NaN,USA,Cosimo Molyneaux

In [26]:
# making dictionary to mapp old index with new

rename_dict = {0:"first", 1:"second",2:'third',4:'fourth'}
df.rename(index = rename_dict).head()

,id,first_name,last_name,full_name2,email,gender,city,state,postcode,Country,full_name
first,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,San Diego,California,92127.0,USA,Romain Southcott
second,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,El Paso,Texas,NaN,USA,Cosimo Molyneaux
third,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,San Antonio,Texas,78220.0,USA,Bambi Westrip
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,Memphis,Tennessee,38150.0,USA,Roarke Pankettman
fourth,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,NaN,83732.0,USA,Mikaela Althorpe

In [27]:
# Renaming Column
df.rename(columns = {'first_name':'First Name', 'last_name':"Last Name"}).head(2)

,id,First Name,Last Name,full_name2,email,gender,city,state,postcode,Country,full_name
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,San Diego,California,92127.0,USA,Romain Southcott
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,El Paso,Texas,NaN,USA,Cosimo Molyneaux

In [28]:
                                                    # Finding Unique Value along column
unique = df['gender'].unique()
print("Unique genders are: ", unique)

Unique genders are:  ['Male' 'Female' nan]

In [29]:
# counting unique in gender
unique_count = df['gender'].nunique()
print("number of unique values in gender column:",unique_count)

number of unique values in gender column: 2

In [30]:
                                        # type Conversion

<h5><b><center> Join, Merge, Concat

In [31]:
# Concat
df_customers = pd.read_excel('customers.xlsx',sheet_name='customers')
df_purchases = pd.read_excel('customers.xlsx',sheet_name='purchases')
df_products = pd.read_excel('customers.xlsx',sheet_name ='products')

combined = pd.concat([df_customers, df_purchases, df_products],axis = 0)
combined

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Unnamed: 0,purch_date,customer_num,product_num,amount,paid,product,cost,company
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,56,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,55.0,NaN,NaN,NaN,NaN,NaN,Peach - Fresh,$20.53,Zazio
56,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,56.0,NaN,NaN,NaN,NaN,NaN,Muffin Hinge - 211n,$68.63,Fanoodle
57,58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,57.0,NaN,NaN,NaN,NaN,NaN,Bar Bran Honey Nut,$73.05,Yakijo
58,59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58.0,NaN,NaN,NaN,NaN,NaN,"Nut - Almond, Blanched, Whole",$74.28,Eazzy
59,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59.0,NaN,NaN,NaN,NaN,NaN,Table Cloth 90x90 Colour,$41.22,Quinu

In [32]:
combined_row_wise = pd.concat([df_customers, df_purchases, df_products],axis = 1)       # if DF have diff column names , pandas will create new column
combined_row_wise

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,...,purch_date,customer_num,product_num,amount,paid,Unnamed: 0,id,product,cost,company
0,1.0,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,...,2019-01-03 00:00:00,823,27,12,$568.92,0.0,1.0,Liners - Baking Cups,$6.36,Skipfire
1,2.0,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,...,2019-01-03 00:00:00,606,28,14,$395.36,1.0,2.0,Nori Sea Weed - Gold Label,$85.74,Dynazzy
2,3.0,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,...,2019-01-03 00:00:00,955,9,17,$510.17,2.0,3.0,Bar Bran Honey Nut,$65.40,Ntag
3,4.0,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,...,2019-01-03 00:00:00,577,19,3,$68.49,3.0,4.0,Soup - Campbells Beef Stew,$68.16,Photojam
4,5.0,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,...,2019-01-03 00:00:00,429,8,18,$759.42,4.0,5.0,Wine - Shiraz Wolf Blass Premium,$87.39,Eare
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,893,33,5,$411.10,NaN,NaN,NaN,NaN,NaN
5996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,566,23,11,$178.97,NaN,NaN,NaN,NaN,NaN
5997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,114,19,9,$205.47,NaN,NaN,NaN,NaN,NaN
5998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,404,11,20,$429.40,NaN,NaN,NaN,NaN,NaN
5999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,06/20/2019,88,57,4,$274.52,NaN,NaN,NaN,NaN,NaN

In [34]:
# Merge (joins) - joins based on one or more keys.
merged_df = pd.merge(df_customers, df_purchases, on ='id', how ='inner')
merged_df.head(3)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Unnamed: 0,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,0,2019-01-03 00:00:00,823,27,12,$568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,1,2019-01-03 00:00:00,606,28,14,$395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,2,2019-01-03 00:00:00,955,9,17,$510.17

In [35]:
merged_right = pd.merge(df_customers ,df_purchases, on='id',how= 'right')
merged_right

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,Unnamed: 0,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,0,2019-01-03 00:00:00,823,27,12,$568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,1,2019-01-03 00:00:00,606,28,14,$395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,2,2019-01-03 00:00:00,955,9,17,$510.17
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,3,2019-01-03 00:00:00,577,19,3,$68.49
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,4,2019-01-03 00:00:00,429,8,18,$759.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,5996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5995,06/20/2019,893,33,5,$411.10
5996,5997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5996,06/20/2019,566,23,11,$178.97
5997,5998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5997,06/20/2019,114,19,9,$205.47
5998,5999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5998,06/20/2019,404,11,20,$429.40
5999,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5999,06/20/2019,88,57,4,$274.52