In [1]:
import pandas as pd
ser_1 = pd.Series(range(5))
print(ser_1)                    # returns, index   values

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [2]:
ser_2 = pd.Series(range(5), ['a','b','c','d','e'])
print(ser_2)                                            # Now we gave custom index for values, with which we can access the elements later

a    0
b    1
c    2
d    3
e    4
dtype: int64

In [3]:
ser_2['b']

np.int64(1)

In [4]:
ser_2[1]                    # even if we have labeled the elements with alphabets , still we can access it with normal index numbers

C:\Users\sachi\AppData\Local\Temp\ipykernel_22480\352250090.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ser_2[1]                    # even if we have labeled the elements with alphabets , still we can access it with normal index numbers

np.int64(1)

In [5]:
ser_2['a': :2]              # starts from 'a' till last with the step size of 2

a    0
c    2
e    4
dtype: int64

In [6]:
ser_1[0:3]              #in default index STOP items is exclusive but in custom index START and STOP both are inclusive

0    0
1    1
2    2
dtype: int64

<h5> <center> <b> Creating a Series

In [7]:
                                                            # from List
data = [10, 20 , 30 ,40 , 50 ,60]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [8]:
s_custom = pd.Series(data, index = ['a','b','c','d','e','f'])
print(s_custom)

s_custom2 = pd.Series(data,['a','b','c','d','e','f'])
print(s_custom2)                                                         # both of these ways works same ,either mention the index word or not , the second attribute will be taken as index

a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64
a    10
b    20
c    30
d    40
e    50
f    60
dtype: int64

In [9]:
try:
    s= pd.Series(data , ['a','b','c','d'])
    print(s)
except Exception as e:
    print(e)                                    # length of index and values must be same

Length of values (6) does not match length of index (4)

In [10]:
                                                                # from Numpy Array
import numpy as np
s = np.array([10,20,30,40])
s_custom = pd.Series(s, ['w','x','y','z'])
print(s_custom)

w    10
x    20
y    30
z    40
dtype: int64

In [11]:
                                                                # from Dictionary
data_dict = {'a':10, 'b':20, 'c':30, 'd':40}
s= pd.Series(data_dict)
print(s)                                                # we do not need to explicitely create custom index

a    10
b    20
c    30
d    40
dtype: int64

<h5><center><b> Elements access

In [12]:
print(s['a'])
print(s['b'])

10
20

In [13]:
data = [1,3,5,8]
s= pd.Series(data, ['a','b','c','d'])
print(s['a':'c'])                               # both start and stop and inclusive in custom indexing

a    1
b    3
c    5
dtype: int64

<h5><center><b> Attributes of Series (Describes the Data)

In [14]:
city = ['mumbai','panaji','gandhinagar','bhopal','amritsar']
state = ['Maharashtra','Goa','Gujrat','MP','Punjab']
s_cap = pd.Series(city , index = state)
print(s_cap)

Maharashtra         mumbai
Goa                 panaji
Gujrat         gandhinagar
MP                  bhopal
Punjab            amritsar
dtype: object

In [15]:
print(s_cap.index)                              # gives the index values assigned to values

Index(['Maharashtra', 'Goa', 'Gujrat', 'MP', 'Punjab'], dtype='object')

In [16]:
print(s_cap.values)                             # gives values

['mumbai' 'panaji' 'gandhinagar' 'bhopal' 'amritsar']

In [17]:
print(s_cap.dtype)                              # gives data type of values

object

In [18]:
print(s_cap.shape)                              # gives shape of series or the number of elements

(5,)

In [19]:
s_cap.name                                      # returns nothing , which means there is no name assigned to the series we have created

In [20]:
s_cap.name = "Capital"
print(s_cap)                                    # now we can see the name as Capital

Maharashtra         mumbai
Goa                 panaji
Gujrat         gandhinagar
MP                  bhopal
Punjab            amritsar
Name: Capital, dtype: object

In [21]:
s_cap.size                                  # gives the number of elements in a series

5

In [22]:
s_cap.empty                                 # returns True if it is empty, else False

False

In [23]:
s_cap.hasnans                               # checks if there is any None value in series, if any returns True

False

In [24]:
ser_4 = pd.Series([1,2,3,None,4])
print(ser_4)                                # Nan has float data type therefore it converts rest data points to float

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
dtype: float64

In [25]:
ser_4.hasnans                               # True ,means we have None value in it

True

In [26]:
ser_4.is_unique                             # True , if all elements are unique

True

In [27]:
ser_4.ndim                                  # gives number of dimension, (always 1 for Series)

1

In [28]:
dt = pd.array([1,2,4,6,3,4])
print(dt.dtype)                             # as pandas built over Numpy so we can create array with pd module

Int64

<h5><b><center> Methods of series ( Performs action or calculations)

In [29]:
s_cap.head(2)                               # returns first 5 values by default

Maharashtra    mumbai
Goa            panaji
Name: Capital, dtype: object

In [30]:
s_cap.tail()

Maharashtra         mumbai
Goa                 panaji
Gujrat         gandhinagar
MP                  bhopal
Punjab            amritsar
Name: Capital, dtype: object

In [31]:
s_cap.describe()                                # gives descriptive stats

count          5
unique         5
top       mumbai
freq           1
Name: Capital, dtype: object

In [32]:
ser_4.describe()

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
dtype: float64

In [33]:
ser_4.value_counts()                                # gives count of unique Values

1.0    1
2.0    1
3.0    1
4.0    1
Name: count, dtype: int64

In [34]:
ser_4.sort_values()                                 # sorts the series by its values

0    1.0
1    2.0
2    3.0
4    4.0
3    NaN
dtype: float64

In [35]:
ser_4.sort_values(ascending =False)                 # sorts in descending order

4    4.0
2    3.0
1    2.0
0    1.0
3    NaN
dtype: float64

In [36]:
ser_4.sort_index()

0    1.0
1    2.0
2    3.0
3    NaN
4    4.0
dtype: float64

In [37]:
s_cap

Maharashtra         mumbai
Goa                 panaji
Gujrat         gandhinagar
MP                  bhopal
Punjab            amritsar
Name: Capital, dtype: object

In [38]:
s_cap.drop('MP')                        # removes specified index from  series

Maharashtra         mumbai
Goa                 panaji
Gujrat         gandhinagar
Punjab            amritsar
Name: Capital, dtype: object

In [39]:
s_cap                                   # as we can see we dropped the MP but still there is Mp in the Series, thats because we didnt assign the operation to series itself

Maharashtra         mumbai
Goa                 panaji
Gujrat         gandhinagar
MP                  bhopal
Punjab            amritsar
Name: Capital, dtype: object

In [40]:
s_cap =s_cap.drop('MP')
s_cap                                                       # now its permenently removed

Maharashtra         mumbai
Goa                 panaji
Gujrat         gandhinagar
Punjab            amritsar
Name: Capital, dtype: object

In [41]:
s_cap.replace('mumbai','bombay')

Maharashtra         bombay
Goa                 panaji
Gujrat         gandhinagar
Punjab            amritsar
Name: Capital, dtype: object

In [42]:
ser_4.isnull()                              # wherever there is null value in the series it returns true

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [43]:
ser_4.isnull().sum()                        # summing up will result in total count of Null values(coz of boolean value sum)

np.int64(1)

<h5><b><center> Mathematical Operations on Series

In [1]:
import pandas as pd

seriesA = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e'])
seriesB = pd.Series([10,20,-10,-50,100], ['z','y','a','c','e'])

In [3]:
# Addition
result  = seriesA + seriesB
print("Addition of seriesA and seriesB is:\n", result)

Addition of seriesA and seriesB is:
 a     -9.0
b      NaN
c    -47.0
d      NaN
e    105.0
y      NaN
z      NaN
dtype: float64

In [4]:
# we can handle these NaN values by dropping them or fillinng them with something else
result_filled = result.fillna(0)
print("Addition result after filling NaN with 0:\n",result_filled)

Addition result after filling NaN with 0:
 a     -9.0
b      0.0
c    -47.0
d      0.0
e    105.0
y      0.0
z      0.0
dtype: float64

In [5]:
result_dropped = result.dropna()
print("Addition result after dropping NaN values:\n",result_dropped)

Addition result after dropping NaN values:
 a     -9.0
c    -47.0
e    105.0
dtype: float64

In [6]:
# Subtraction
result = seriesA - seriesB
print("Subtraction of seriesB from seriesA:\n",result)

Subtraction of seriesB from seriesA:
 a    11.0
b     NaN
c    53.0
d     NaN
e   -95.0
y     NaN
z     NaN
dtype: float64

In [7]:
# MUltiplication
result = seriesA * seriesB
print("Multiplication of seriesA and seriesB:\n",result)

Multiplication of seriesA and seriesB:
 a    -10.0
b      NaN
c   -150.0
d      NaN
e    500.0
y      NaN
z      NaN
dtype: float64

In [8]:
# Division
result = seriesA / seriesB
print("Division of seriesA by seriesB:\n",result)

Division of seriesA by seriesB:
 a   -0.10
b     NaN
c   -0.06
d     NaN
e    0.05
y     NaN
z     NaN
dtype: float64

<h4><b><center> DataFrame

In [2]:
import pandas as pd
df_1 = pd.DataFrame([[1,4,7],[2,5,8],[3,6,9]])
print(df_1)

   0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [3]:
df_1

   0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

<h5><b><center> Creating Dataframe

In [4]:
                                                    #Creating an empty DataFrame
empty_df = pd.DataFrame()
empty_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
                                                    # creating DF from Numpy Array
data = np.array([[33,'mumbai'],[44,'pune'],[55,'nashik'],[66,'nagar']])
df= pd.DataFrame(data, columns=['Id','City'], index= ['a','b','c','d'])             # index is used here for custom row
df

   Id    City
a  33  mumbai
b  44    pune
c  55  nashik
d  66   nagar

In [13]:
                                                    # Creating DF from List of Dictionaries
data = [{'Name':'Sachin','Age':21,'City':'nagar'},{'Name':'Praful','Age':26,'City':'Nashik'},{'Name':'Neha','Age':25,'City':'Pune'}]
df = pd.DataFrame(data)
df

     Name  Age    City
0  Sachin   21   nagar
1  Praful   26  Nashik
2    Neha   25    Pune

In [17]:
                                                    # Creating DF from Excel/CSV file
df = pd.read_csv("D:\\Downloads\\flight_delays_train.csv")
df.head()

,Month,DayofMonth,DayOfWeek,DepTime,UniqueCarrier,Origin,Dest,Distance,dep_delayed_15min
0,c-8,c-21,c-7,1934,AA,ATL,DFW,732,N
1,c-4,c-20,c-3,1548,US,PIT,MCO,834,N
2,c-9,c-2,c-5,1422,XE,RDU,CLE,416,N
3,c-11,c-25,c-6,1015,OO,DEN,MEM,872,N
4,c-10,c-7,c-6,1828,WN,MDW,OMA,423,Y

In [31]:
df = pd.read_excel(r"D:\Downloads\techcode.xlsx")       # here \t was reading as tab,so we used 'r' so that it will ignore all escape sequence  
df.tail(2)

,Issue ID,First Name,Last Name,ATM ID,Email,Symptom,Photo,Description,Category,Assigned Tech,Date Created,Resolved,Notes,Date Resolved
9,537b04c3,Quick,lab,ATM007,NaN,ATM wont turn on,NaN,NaN,General Issues,Shelley Ginder,2023-08-01 22:26:00,False,NaN,NaN
10,f80932db,Freeda,NaN,ATM123,NaN,Card reader not working,NaN,NaN,General Issues,Shelley Ginder,2023-08-01 22:26:00,False,NaN,NaN

In [26]:
import pandas as pd
df = pd.read_excel("D:\\Downloads\\techcode.xlsx",sheet_name="Tickets")         # we can also specify the sheet name
df.head(3)

,Issue ID,First Name,Last Name,ATM ID,Email,Symptom,Photo,Description,Category,Assigned Tech,Date Created,Resolved,Notes,Date Resolved
0,0d5ff8ed8d,Fredrick,Thompson,33562,fredrick.thompson@fakeitcompany.com,ATM wont turn on,NaN,ATM screen is black,General Issues,Shelley Ginder,2016-10-13 18:06:00,True,NaN,NaN
1,d9c1547599,Patsy,Sheehan,66722,patsy.sheehan@fakeitcompany.com,Card reader not working,NaN,The ATM is not recognizing cards,General Issues,Justin Sample,2016-10-14 18:06:00,True,NaN,NaN
2,e0cb653f42,Jon,Snow,3351,jon.snow@fakeitcompany.com,Broken keypad,NaN,The 2 on the keypad isn't working,General Issues,Shelley Ginder,2016-10-15 18:06:00,True,NaN,NaN

<h5><b><center> Accesing DF data

In [ ]:
df.columns                              # returns the list of all columns

Index(['Issue ID', 'First Name', 'Last Name', 'ATM ID', 'Email', 'Symptom',
       'Photo', 'Description', 'Category', 'Assigned Tech', 'Date Created',
       'Resolved', 'Notes', 'Date Resolved'],
      dtype='object')

In [ ]:
df['First Name']                        # returns the column data which has 'First Name' as column name

0      Fredrick
1         Patsy
2           Jon
3     Alexander
4         Verna
5         Megan
6          Paul
7      Danielle
8     Alexander
9         Quick
10       Freeda
Name: First Name, dtype: object

In [ ]:
df[['First Name', 'Last Name']]             # allows us to get data of multiple columns

   First Name Last Name
0    Fredrick  Thompson
1       Patsy   Sheehan
2         Jon      Snow
3   Alexander     Ramos
4       Verna     Moore
5       Megan   Iverson
6        Paul     Edson
7    Danielle      West
8   Alexander     Ramos
9       Quick       lab
10     Freeda       NaN

In [ ]:
df.loc[ : ,"First Name"]                # give all rows for column "First Name"  ( row, column  )

0      Fredrick
1         Patsy
2           Jon
3     Alexander
4         Verna
5         Megan
6          Paul
7      Danielle
8     Alexander
9         Quick
10       Freeda
Name: First Name, dtype: object

In [ ]:
df.loc[ :5 ,['First Name','Last Name','Email']]                 # gives first 6 rows(coz all inclusive) for First, Last Name and Email column

  First Name Last Name                                Email
0   Fredrick  Thompson  fredrick.thompson@fakeitcompany.com
1      Patsy   Sheehan      patsy.sheehan@fakeitcompany.com
2        Jon      Snow           jon.snow@fakeitcompany.com
3  Alexander     Ramos    alexander.ramos@fakeitcompany.com
4      Verna     Moore        verna.moore@fakeitcompany.com
5      Megan   Iverson      megan.iverson@fakeitcompany.com

In [ ]:
df.loc[:3, :'Email']                        # it gives all columns from start till email

     Issue ID First Name Last Name ATM ID                                Email
0  0d5ff8ed8d   Fredrick  Thompson  33562  fredrick.thompson@fakeitcompany.com
1  d9c1547599      Patsy   Sheehan  66722      patsy.sheehan@fakeitcompany.com
2  e0cb653f42        Jon      Snow   3351           jon.snow@fakeitcompany.com
3  94803beda8  Alexander     Ramos  37490    alexander.ramos@fakeitcompany.com

In [45]:
# .iloc (index based)

df.iloc[ :3 , 1]

0    Fredrick
1       Patsy
2         Jon
Name: First Name, dtype: object

In [ ]:
df.iloc[:3 ,:5]                                         # first 3 rows with first 5 columns

     Issue ID First Name Last Name ATM ID                                Email
0  0d5ff8ed8d   Fredrick  Thompson  33562  fredrick.thompson@fakeitcompany.com
1  d9c1547599      Patsy   Sheehan  66722      patsy.sheehan@fakeitcompany.com
2  e0cb653f42        Jon      Snow   3351           jon.snow@fakeitcompany.com

<h5> <b> Boolean Indexing

In [49]:
bool_ser =df['Assigned Tech'] =='Shelley Ginder'                          # comaprison with particular requirment
bool_ser

0      True
1     False
2      True
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10     True
Name: Assigned Tech, dtype: bool

In [ ]:
df.loc[bool_ser, 'First Name':'Assigned Tech':2]            # selects all with 'Shelley Ginder'

,First Name,ATM ID,Symptom,Description,Assigned Tech
0,Fredrick,33562,ATM wont turn on,ATM screen is black,Shelley Ginder
2,Jon,3351,Broken keypad,The 2 on the keypad isn't working,Shelley Ginder
9,Quick,ATM007,ATM wont turn on,NaN,Shelley Ginder
10,Freeda,ATM123,Card reader not working,NaN,Shelley Ginder

In [54]:
(df['Assigned Tech']=='Shelley Ginder' ) | (df['Resolved']==False)        # Combining two conditions

0      True
1     False
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10     True
dtype: bool

In [1]:
                                                    # Range to Series 
# Define Range , convert into numpy , convert into series

import numpy as np
import pandas as pd

num = range(1,11)
array = np.array(num)
series = pd.Series(array)
print(series)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64

In [2]:
                                                # Series Game
# each student roll number from 23070 to 23080 (inclusive), use roll number as index , default value as Delhi , name the series as "Student Info"
import pandas as pd

roll_num = range(23070, 23081)
value = 'Delhi'
std_info = pd.Series(value, roll_num)

std_info.name = 'Student info'
print(std_info)

23070    Delhi
23071    Delhi
23072    Delhi
23073    Delhi
23074    Delhi
23075    Delhi
23076    Delhi
23077    Delhi
23078    Delhi
23079    Delhi
23080    Delhi
Name: Student info, dtype: object

In [3]:
                                                    # Extract index and Values
# Extract index of series , extract values of series 

data = {'Delhi': 31.0, 'Mumbai': 20.0, 'Chennai': 10.5, 'Kolkata': 14.0}
series = pd.Series(data)

city_index = series.index
city_population = series.values

print(city_index)
print(city_population)

Index(['Delhi', 'Mumbai', 'Chennai', 'Kolkata'], dtype='object')
[31.  20.  10.5 14. ]

In [6]:
                                                    # Series Properties
# find data type , find number of elements ,identify dimensions, printn shape

data = [10, 20.5, "Python", True, None]
series = pd.Series(data)

print("Data type:",series.dtype)
print("Number of elements in a series:",series.size)
print("Dimensionality of series:",series.ndim)
print("Shape of the series:",series.shape)

Data type: object
Number of elements in a series: 5
Dimensionality of series: 1
Shape of the series: (5,)

In [7]:
                                                    # Fill series with factors
# find all the factors 365, print resulting series

factors =[]
for i in range(1,366):
    if 365%i ==0:
        factors.append(i)

series = pd.Series(factors)
print(series)

0      1
1      5
2     73
3    365
dtype: int64

In [8]:
                                                    # Series Cleaning and Multiplication
# check for NaN values ,  drop NaN values, perform multiplication, if multiplication result has NaN Values replace them with -1

series1 = pd.Series([10, np.nan, 30, 40, 50, np.nan, 70])
series2 = pd.Series([2, 3, np.nan, 5, 6, 7, np.nan])


series1_NaN = series1.dropna()
series2_NaN = series2.dropna()                      # dropping NaN values

series_multi = series1_NaN * series2_NaN            # Series Multiplication

result_filled = series_multi.fillna(-1)             # filling NaN values with -1
print(result_filled)

0     20.0
1     -1.0
2     -1.0
3    200.0
4    300.0
5     -1.0
6     -1.0
dtype: float64

In [ ]:
                                                    # DataFrame from dictionary, and accessing it
# print top two rows, and bottom 3 rows

data = {
    'Employee_ID': [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    'Name': ['Aarav', 'Vivaan', 'Aditya', 'Vihaan', 'Arjun', 'Sai', 'Ishaan', 'Krishna', 'Anaya', 'Pooja'],
    'Age': [25, 30, 35, 40, 45, 28, 33, 38, 27, 32],
    'Department': ['HR', 'Finance', 'IT', 'IT', 'HR', 'Finance', 'IT', 'HR', 'Finance', 'IT'],
    'Salary': [50000, 60000, 70000, 80000, 75000, 65000, 70000, 72000, 68000, 75000]
}

# Write your code from here
df = pd.DataFrame(data)
print(df.head(2))                       # or df[:2]
print(df.tail(3))

   Employee_ID    Name  Age Department  Salary
0         1001   Aarav   25         HR   50000
1         1002  Vivaan   30    Finance   60000
   Employee_ID     Name  Age Department  Salary
7         1008  Krishna   38         HR   72000
8         1009    Anaya   27    Finance   68000
9         1010    Pooja   32         IT   75000

In [15]:
                                                    # DataFrame from CSV
# read CSV , find shape, display name and count of every unique in the "Embarked"

df = pd.read_csv('train.csv')
print(df.shape)
print(df['Embarked'].value_counts())

(418, 12)
Embarked
S    270
C    102
Q     46
Name: count, dtype: int64

In [16]:
                                                    # Filter rows in Data Frame
# Filter out the rows where the "Embarked" column is 'C' and the "Sex" column is 'female'.


df = pd.read_csv('train.csv')
df['Embarked'] == 'C'
df['Sex'] == 'female'
filtered_df = df[(df['Embarked'] == 'C') & (df['Sex'] == 'female')]

print(filtered_df.shape)

(40, 12)

In [18]:
                                                    # Null Count in Dataframe
# find total number of null values in entire dataframe

df = pd.read_csv('train.csv')
missing = df.isnull().sum().sum()                    #.sum()  -sums up True value, .sum() - sums up the series
print(missing)

414

In [20]:
                                                    # Total Elements in subset
# Select first 100 rows and specific range of even-indexed columns

df = pd.read_csv('train.csv')

filtered = df.iloc[:100,2:11:2]
print("Filtering the dataset",filtered)
print(filtered.size)

Filtering the dataset     Pclass     Sex  SibSp             Ticket Cabin
0        3    male      0             330911   NaN
1        3  female      1             363272   NaN
2        2    male      0             240276   NaN
3        3    male      0             315154   NaN
4        3  female      1            3101298   NaN
..     ...     ...    ...                ...   ...
95       3    male      0             350033   NaN
96       1  female      1              19877   C46
97       3    male      0  STON/O 2. 3101268   NaN
98       3  female      0             347471   NaN
99       3    male      0         A./5. 3338   NaN

[100 rows x 5 columns]
500